version: "3.7"
services:
  docker_api_proxy:
    image: tecnativa/docker-socket-proxy
    environment:
      - CONTAINERS=1
      - NETWORKS=1
      - TASKS=1
    deploy:
      placement:
        constraints:
          - node.role == manager
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - network_wifi
      - network_cable
      - network_3g
  gw_cable:
    image: wotsim
    command: ["gateway", "delay --time 5 --jitter 1 --distribution normal"]
    privileged: true
    hostname: gw_cable
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - network_cable
    labels:
      - "org.fundacionctic.wotsim.gw"
  gw_wifi:
    image: wotsim
    command: ["gateway", "delay --time 15 --jitter 10 --distribution normal"]
    privileged: true
    hostname: gw_wifi
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - network_wifi
    labels:
      - "org.fundacionctic.wotsim.gw"
  gw_3g:
    image: wotsim
    command:
      [
        "gateway",
        "delay --time 100 --jitter 50 --distribution normal",
        "rate --rate 200kbit",
      ]
    privileged: true
    hostname: gw_3g
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - network_3g
    labels:
      - "org.fundacionctic.wotsim.gw"
  node_wifi_1:
    image: wotsim
    command: ["node"]
    privileged: true
    hostname: node_wifi_1
    networks:
      - network_wifi
    depends_on:
      - docker_api_proxy
      - gw_wifi
  node_wifi_2:
    image: wotsim
    command: ["node"]
    privileged: true
    hostname: node_wifi_2
    networks:
      - network_wifi
    depends_on:
      - docker_api_proxy
      - gw_wifi
  node_cable_1:
    image: wotsim
    command: ["node"]
    privileged: true
    hostname: node_cable_1
    networks:
      - network_cable
      - network_3g
    depends_on:
      - docker_api_proxy
      - gw_cable
      - gw_3g
    environment:
      - DEFAULT_BROKER=mqtt://broker_1.network_3g
  node_cable_2:
    image: wotsim
    command: ["node"]
    privileged: true
    hostname: node_cable_2
    networks:
      - network_cable
      - network_3g
    depends_on:
      - docker_api_proxy
      - gw_cable
      - gw_3g
    environment:
      - DEFAULT_BROKER=mqtt://broker_1.network_3g
  node_wifi_cable_1:
    image: wotsim
    command: ["node"]
    privileged: true
    hostname: node_wifi_cable_1
    networks:
      - network_wifi
      - network_cable
    depends_on:
      - docker_api_proxy
      - gw_cable
      - gw_wifi
  broker_1:
    image: wotsim
    command: ["broker"]
    privileged: true
    hostname: broker_1
    networks:
      - network_3g
    depends_on:
      - docker_api_proxy
      - gw_3g
networks:
  network_cable:
    driver: overlay
    name: network_cable
    attachable: true
    labels:
      - "org.fundacionctic.wotsim.net"
  network_wifi:
    driver: overlay
    name: network_wifi
    attachable: true
    labels:
      - "org.fundacionctic.wotsim.net"
  network_3g:
    driver: overlay
    name: network_3g
    attachable: true
    labels:
      - "org.fundacionctic.wotsim.net"
