version: "3.7"
services:
  docker_api_proxy:
    image: tecnativa/docker-socket-proxy
    hostname: docker_api_proxy
    ports:
      - "2375"
    environment:
      - CONTAINERS=1
      - NETWORKS=1
      - TASKS=1
    deploy:
      placement:
        constraints:
          - node.role == manager
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - network_3g
      - network_cable
  node_3g_1:
    image: wotsim
    privileged: true
    hostname: node_3g_1
    networks:
      - network_3g
    depends_on:
      - docker_api_proxy
      - gw_3g
  node_3g_2:
    image: wotsim
    privileged: true
    hostname: node_3g_2
    networks:
      - network_3g
    depends_on:
      - docker_api_proxy  
      - gw_3g
  gw_3g:
    image: wotsim
    command: ["sleep", "infinity"]
    hostname: gw_3g
    networks:
      - network_3g
    labels:
      - "org.fundacionctic.wotsim.gw"
  node_cable_1:
    image: wotsim
    privileged: true
    hostname: node_cable_1
    networks:
      - network_cable
    depends_on:
      - docker_api_proxy  
      - gw_cable
  node_cable_2:
    image: wotsim
    privileged: true
    hostname: node_cable_2
    networks:
      - network_cable
    depends_on:
      - docker_api_proxy
      - gw_cable
  gw_cable:
    image: wotsim
    command: ["sleep", "infinity"]
    hostname: gw_cable
    networks:
      - network_cable
    labels:
      - "org.fundacionctic.wotsim.gw"
  node_3g_cable_1:
    image: wotsim
    privileged: true
    hostname: node_3g_cable_1
    networks:
      - network_3g
      - network_cable
    depends_on:
      - docker_api_proxy
      - gw_cable
      - gw_3g
networks:
  network_3g:
    driver: overlay
    attachable: true
    labels:
      - "org.fundacionctic.wotsim.net"
  network_cable:
    driver: overlay
    attachable: true
    labels:
      - "org.fundacionctic.wotsim.net"
