version: "3.7"
services:
  docker_api_proxy:
    image: tecnativa/docker-socket-proxy
    environment:
      - CONTAINERS=1
      - NETWORKS=1
      - TASKS=1
      - PATCH_PRIVILEGED=1
    deploy:
      placement:
        constraints:
          - node.role == manager
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - network_wifi
      - network_cable
      - network_3g_broker
  redis:
    image: redis:5
    networks:
      - network_wifi
      - network_cable
      - network_3g_broker
  gw_cable:
    image: wotsim
    command: ["gateway", "delay --time 5 --jitter 1 --distribution normal"]
    privileged: true
    hostname: "{{.Task.Name}}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - network_cable
    labels:
      - "org.fundacionctic.wotsim.gw"
    environment:
      - PATCH_PRIVILEGED=1
  gw_wifi:
    image: wotsim
    command: ["gateway", "delay --time 15 --jitter 10 --distribution normal"]
    privileged: true
    hostname: "{{.Task.Name}}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - network_wifi
    labels:
      - "org.fundacionctic.wotsim.gw"
    environment:
      - PATCH_PRIVILEGED=1
  gw_3g_broker:
    image: wotsim
    command:
      [
        "gateway",
        "delay --time 100 --jitter 50 --distribution normal",
        "rate --rate 200kbit",
      ]
    privileged: true
    hostname: "{{.Task.Name}}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - network_3g_broker
    labels:
      - "org.fundacionctic.wotsim.gw"
    environment:
      - PATCH_PRIVILEGED=1
  node_wifi_1:
    image: wotsim
    command:
      [
        "app",
        "--path",
        "/root/wotsim/examples/time_app.py",
        "--enable-http",
        "--enable-coap",
      ]
    privileged: true
    hostname: "{{.Task.Name}}"
    networks:
      - network_wifi
    depends_on:
      - docker_api_proxy
      - gw_wifi
    environment:
      - PATCH_PRIVILEGED=1
  node_wifi_2:
    image: wotsim
    command:
      [
        "app",
        "--path",
        "/root/wotsim/examples/subscriber_app.py",
        "--func-param",
        "servient_host",
        "node_wifi_cable_1.network_wifi",
        "--func-param",
        "thing_id",
        "urn:org:fundacionctic:thing:time",
      ]
    privileged: true
    hostname: "{{.Task.Name}}"
    networks:
      - network_wifi
      - network_3g_broker
    depends_on:
      - docker_api_proxy
      - gw_wifi
    environment:
      - PATCH_PRIVILEGED=1
  node_cable_1:
    image: wotsim
    command:
      ["app", "--path", "/root/wotsim/examples/time_app.py", "--enable-ws"]
    privileged: true
    hostname: "{{.Task.Name}}"
    networks:
      - network_cable
      - network_3g_broker
    depends_on:
      - docker_api_proxy
      - gw_cable
      - gw_3g_broker
    environment:
      - PATCH_PRIVILEGED=1
  node_cable_2:
    image: wotsim
    command:
      ["app", "--path", "/root/wotsim/examples/time_app.py", "--enable-ws"]
    privileged: true
    hostname: "{{.Task.Name}}"
    networks:
      - network_cable
      - network_3g_broker
    depends_on:
      - docker_api_proxy
      - gw_cable
      - gw_3g_broker
    environment:
      - PATCH_PRIVILEGED=1
  node_wifi_cable_1:
    image: wotsim
    command:
      ["app", "--path", "/root/wotsim/examples/time_app.py", "--enable-mqtt"]
    privileged: true
    hostname: "{{.Task.Name}}"
    networks:
      - network_wifi
      - network_cable
      - network_3g_broker
    depends_on:
      - docker_api_proxy
      - gw_cable
      - gw_wifi
    environment:
      - PATCH_PRIVILEGED=1
      - MQTT_BROKER_HOST=broker_1.network_3g_broker
  broker_1:
    image: wotsim
    command: ["broker"]
    privileged: true
    hostname: "{{.Task.Name}}"
    networks:
      - network_3g_broker
    depends_on:
      - docker_api_proxy
      - gw_3g_broker
    environment:
      - PATCH_PRIVILEGED=1
networks:
  network_cable:
    driver: overlay
    name: network_cable
    attachable: true
    labels:
      - "org.fundacionctic.wotsim.net"
  network_wifi:
    driver: overlay
    name: network_wifi
    attachable: true
    labels:
      - "org.fundacionctic.wotsim.net"
  network_3g_broker:
    driver: overlay
    name: network_3g_broker
    attachable: true
    labels:
      - "org.fundacionctic.wotsim.net"
