networks:
  mobile_2g:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: mobile_2g
  srvnet_mongo_clock_http:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.servicenet: ''
    name: srvnet_mongo_clock_http
  srvnet_mongo_clock_sub_http:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.servicenet: ''
    name: srvnet_mongo_clock_sub_http
  wifi:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: wifi
services:
  broker:
    cap_add:
    - ALL
    command:
    - broker
    depends_on:
    - gw_mobile_2g
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.broker: ''
    networks:
    - mobile_2g
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  clock_http:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_clock
    - --enable-http
    depends_on:
    - gw_wifi
    - redis
    - docker_api_proxy
    deploy:
      replicas: 2
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - wifi
    - srvnet_mongo_clock_http
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  clock_mqtt:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_clock
    - --enable-mqtt
    depends_on:
    - gw_wifi
    - redis
    - gw_mobile_2g
    - docker_api_proxy
    deploy:
      replicas: 2
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      MQTT_BROKER_HOST: broker.mobile_2g
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - wifi
    - mobile_2g
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  clock_property_reader:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_reader
    - --func-param
    - servient_host
    - clock_http.wifi
    - --func-param
    - thing_id
    - urn:org:fundacionctic:thing:clock
    depends_on:
    - gw_wifi
    - redis
    - docker_api_proxy
    deploy:
      replicas: 2
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - wifi
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  clock_sub_http:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_subscriber
    - --func-param
    - servient_host
    - clock_http.wifi
    - --func-param
    - thing_id
    - urn:org:fundacionctic:thing:clock
    depends_on:
    - gw_wifi
    - redis
    - docker_api_proxy
    deploy:
      replicas: 4
      resources:
        limits:
          memory: 200M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - wifi
    - srvnet_mongo_clock_sub_http
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  clock_sub_mqtt:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_subscriber
    - --func-param
    - servient_host
    - clock_mqtt.wifi
    - --func-param
    - thing_id
    - urn:org:fundacionctic:thing:clock
    depends_on:
    - gw_wifi
    - redis
    - gw_mobile_2g
    - docker_api_proxy
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 200M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - wifi
    - mobile_2g
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  docker_api_proxy:
    cap_add:
    - ALL
    deploy:
      placement:
        constraints:
        - node.role == manager
    environment:
      CONTAINERS: '1'
      NETWORKS: '1'
      NODES: '1'
      SERVICES: '1'
      TASKS: '1'
    image: tecnativa/docker-socket-proxy
    networks:
    - wifi
    - mobile_2g
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  error:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_error
    depends_on:
    - gw_wifi
    - redis
    - docker_api_proxy
    deploy:
      replicas: 1
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - wifi
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_mobile_2g:
    cap_add:
    - ALL
    command:
    - gateway
    - '{"latency": 700, "jitter": 100, "rate": "100kbit"}'
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - mobile_2g
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_wifi:
    cap_add:
    - ALL
    command:
    - gateway
    - '{"latency": 25, "jitter": 5, "rate": "50mbit"}'
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - wifi
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: mongo:4
    labels:
      org.fundacionctic.wotemu.service: ''
    networks:
    - srvnet_mongo_clock_http
    - srvnet_mongo_clock_sub_http
  redis:
    image: redis:5
    labels:
      org.fundacionctic.wotemu.redis: ''
    networks:
    - wifi
    - mobile_2g
    ports:
    - '6379'
  worker:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_worker
    - --enable-ws
    depends_on:
    - redis
    - gw_mobile_2g
    - docker_api_proxy
    deploy:
      replicas: 1
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - mobile_2g
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  worker_caller:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_caller
    - --func-param
    - servient_host
    - worker.mobile_2g
    - --func-param
    - thing_id
    - urn:org:fundacionctic:thing:worker
    depends_on:
    - redis
    - gw_mobile_2g
    - docker_api_proxy
    deploy:
      replicas: 2
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - mobile_2g
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
version: '3.7'
