networks:
  cloud_user:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: cloud_user
  edge_link_location_1:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: edge_link_location_1
  edge_link_location_2:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: edge_link_location_2
  field_location_1:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: field_location_1
  field_location_2:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: field_location_2
  srvnet_mongo_historian:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.servicenet: ''
    name: srvnet_mongo_historian
services:
  camera_location_1_0:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - redis
    - docker_api_proxy
    - gw_field_location_1
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field_location_1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_location_1_1:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - redis
    - docker_api_proxy
    - gw_field_location_1
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field_location_1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_location_1_2:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - redis
    - docker_api_proxy
    - gw_field_location_1
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field_location_1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_location_2_0:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - redis
    - docker_api_proxy
    - gw_field_location_2
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field_location_2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  detector_location_1:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_detector
    - --func-param
    - cameras
    - '[{"servient_host": "camera_location_1_0.field_location_1"}, {"servient_host":
      "camera_location_1_1.field_location_1"}, {"servient_host": "camera_location_1_2.field_location_1"}]'
    - --enable-http
    depends_on:
    - docker_api_proxy
    - gw_edge_link_location_1
    - redis
    - gw_field_location_1
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 600
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field_location_1
    - edge_link_location_1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  detector_location_2:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_detector
    - --func-param
    - cameras
    - '[{"servient_host": "camera_location_2_0.field_location_2"}]'
    - --enable-http
    depends_on:
    - redis
    - docker_api_proxy
    - gw_edge_link_location_2
    - gw_field_location_2
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 600
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field_location_2
    - edge_link_location_2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  docker_api_proxy:
    cap_add:
    - ALL
    deploy:
      placement:
        constraints:
        - node.role == manager
    environment:
      CONTAINERS: '1'
      NETWORKS: '1'
      NODES: '1'
      SERVICES: '1'
      TASKS: '1'
    image: tecnativa/docker-socket-proxy
    networks:
    - field_location_2
    - edge_link_location_1
    - field_location_1
    - cloud_user
    - edge_link_location_2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_cloud_user:
    cap_add:
    - ALL
    command:
    - gateway
    - delay --time 5 --jitter 5 --distribution normal
    - rate --rate 100mbit
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - cloud_user
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_edge_link_location_1:
    cap_add:
    - ALL
    command:
    - gateway
    - delay --time 300 --jitter 150 --distribution normal
    - rate --rate 1500kbit
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - edge_link_location_1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_edge_link_location_2:
    cap_add:
    - ALL
    command:
    - gateway
    - delay --time 300 --jitter 150 --distribution normal
    - rate --rate 1500kbit
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - edge_link_location_2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_field_location_1:
    cap_add:
    - ALL
    command:
    - gateway
    - delay --time 25 --jitter 5 --distribution normal
    - rate --rate 50mbit
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - field_location_1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_field_location_2:
    cap_add:
    - ALL
    command:
    - gateway
    - delay --time 25 --jitter 5 --distribution normal
    - rate --rate 50mbit
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - field_location_2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  historian:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_mongo_historian
    - --func-param
    - mongo_uri
    - mongodb://mongo
    - --func-param
    - observed_things
    - '[{"servient_host": "detector_location_1.edge_link_location_1", "thing_id":
      "urn:org:fundacionctic:thing:wotemu:detector"}, {"servient_host": "detector_location_2.edge_link_location_2",
      "thing_id": "urn:org:fundacionctic:thing:wotemu:detector"}]'
    - --enable-http
    depends_on:
    - gw_cloud_user
    - docker_api_proxy
    - gw_edge_link_location_1
    - gw_edge_link_location_2
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - srvnet_mongo_historian
    - cloud_user
    - edge_link_location_2
    - edge_link_location_1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: mongo:4
    labels:
      org.fundacionctic.wotemu.service: ''
    networks:
    - srvnet_mongo_historian
  redis:
    image: redis:5
    labels:
      org.fundacionctic.wotemu.redis: ''
    networks:
    - field_location_2
    - edge_link_location_1
    - field_location_1
    - cloud_user
    - edge_link_location_2
    ports:
    - '6379'
  user:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_caller
    - --func-param
    - servient_host
    - historian.cloud_user
    - --func-param
    - thing_id
    - urn:org:fundacionctic:thing:historian
    - --func-param
    - params
    - '{"write": null}'
    - --func-param
    - lambd
    - '3'
    depends_on:
    - redis
    - docker_api_proxy
    - gw_cloud_user
    deploy:
      replicas: 3
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - cloud_user
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
version: '3.7'
