networks:
  cloud:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: cloud
  cloud_user:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: cloud_user
  edge_2g_loc1:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: edge_2g_loc1
  edge_3g_loc2:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: edge_3g_loc2
  srvnet_mongo_cloud:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.servicenet: ''
    name: srvnet_mongo_cloud
services:
  broker:
    cap_add:
    - ALL
    command:
    - broker
    depends_on:
    - gw_edge_2g_loc1
    - gw_edge_3g_loc2
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.broker: ''
    networks:
    - edge_2g_loc1
    - edge_3g_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_loc1_0:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-mqtt
    depends_on:
    - docker_api_proxy
    - gw_edge_2g_loc1
    - redis
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      MQTT_BROKER_HOST: broker.edge_2g_loc1
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - edge_2g_loc1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_loc1_1:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-mqtt
    depends_on:
    - docker_api_proxy
    - gw_edge_2g_loc1
    - redis
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      MQTT_BROKER_HOST: broker.edge_2g_loc1
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - edge_2g_loc1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_loc2_0:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-mqtt
    depends_on:
    - docker_api_proxy
    - gw_edge_3g_loc2
    - redis
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      MQTT_BROKER_HOST: broker.edge_3g_loc2
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - edge_3g_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_loc2_1:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-mqtt
    depends_on:
    - docker_api_proxy
    - gw_edge_3g_loc2
    - redis
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      MQTT_BROKER_HOST: broker.edge_3g_loc2
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - edge_3g_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_loc2_2:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-mqtt
    depends_on:
    - docker_api_proxy
    - gw_edge_3g_loc2
    - redis
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      MQTT_BROKER_HOST: broker.edge_3g_loc2
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - edge_3g_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_loc2_3:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-mqtt
    depends_on:
    - docker_api_proxy
    - gw_edge_3g_loc2
    - redis
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      MQTT_BROKER_HOST: broker.edge_3g_loc2
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - edge_3g_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_loc2_4:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-mqtt
    depends_on:
    - docker_api_proxy
    - gw_edge_3g_loc2
    - redis
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      MQTT_BROKER_HOST: broker.edge_3g_loc2
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - edge_3g_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_loc2_5:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-mqtt
    depends_on:
    - docker_api_proxy
    - gw_edge_3g_loc2
    - redis
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      MQTT_BROKER_HOST: broker.edge_3g_loc2
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - edge_3g_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  cloud:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_mongo_historian
    - --func-param
    - mongo_uri
    - mongodb://mongo
    - --func-param
    - observed_things
    - '[{"servient_host": "detector.cloud", "thing_id": "urn:org:fundacionctic:thing:wotemu:detector"}]'
    - --enable-http
    depends_on:
    - docker_api_proxy
    - gw_cloud
    - redis
    - gw_cloud_user
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - cloud_user
    - srvnet_mongo_cloud
    - cloud
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  detector:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_detector
    - --func-param
    - cameras
    - '[{"servient_host": "camera_loc1_0.edge_2g_loc1"}, {"servient_host": "camera_loc1_1.edge_2g_loc1"},
      {"servient_host": "camera_loc2_0.edge_3g_loc2"}, {"servient_host": "camera_loc2_1.edge_3g_loc2"},
      {"servient_host": "camera_loc2_2.edge_3g_loc2"}, {"servient_host": "camera_loc2_3.edge_3g_loc2"},
      {"servient_host": "camera_loc2_4.edge_3g_loc2"}, {"servient_host": "camera_loc2_5.edge_3g_loc2"}]'
    - --enable-http
    depends_on:
    - gw_edge_2g_loc1
    - gw_cloud
    - docker_api_proxy
    - redis
    - gw_edge_3g_loc2
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - edge_2g_loc1
    - cloud
    - edge_3g_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  docker_api_proxy:
    cap_add:
    - ALL
    deploy:
      placement:
        constraints:
        - node.role == manager
    environment:
      CONTAINERS: '1'
      NETWORKS: '1'
      NODES: '1'
      SERVICES: '1'
      TASKS: '1'
    image: tecnativa/docker-socket-proxy
    networks:
    - edge_3g_loc2
    - cloud_user
    - edge_2g_loc1
    - cloud
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_cloud:
    cap_add:
    - ALL
    command:
    - gateway
    - '{"latency": 5, "jitter": 5, "rate": "100mbit"}'
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - cloud
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_cloud_user:
    cap_add:
    - ALL
    command:
    - gateway
    - '{"latency": 5, "jitter": 5, "rate": "100mbit"}'
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - cloud_user
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_edge_2g_loc1:
    cap_add:
    - ALL
    command:
    - gateway
    - '{"latency": 700, "jitter": 100, "rate": "50kbit"}'
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - edge_2g_loc1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_edge_3g_loc2:
    cap_add:
    - ALL
    command:
    - gateway
    - '{"latency": 300, "jitter": 150, "rate": "1500kbit"}'
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - edge_3g_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: mongo:4
    labels:
      org.fundacionctic.wotemu.service: ''
    networks:
    - srvnet_mongo_cloud
  redis:
    image: redis:5
    labels:
      org.fundacionctic.wotemu.redis: ''
    networks:
    - edge_3g_loc2
    - cloud_user
    - edge_2g_loc1
    - cloud
    ports:
    - '6379'
  user:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_caller
    - --func-param
    - servient_host
    - cloud.cloud_user
    - --func-param
    - thing_id
    - urn:org:fundacionctic:thing:historian
    - --func-param
    - params
    - '{"write": null, "list": null}'
    - --func-param
    - lambd
    - '5'
    depends_on:
    - docker_api_proxy
    - redis
    - gw_cloud_user
    deploy:
      replicas: 5
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - cloud_user
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
version: '3.7'
