networks:
  cloud_user:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: cloud_user
  edge_link:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: edge_link
  field:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: field
services:
  camera_num_0:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - gw_field
    - docker_api_proxy
    - redis
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_num_1:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - gw_field
    - docker_api_proxy
    - redis
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_num_2:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - gw_field
    - docker_api_proxy
    - redis
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_num_3:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - gw_field
    - docker_api_proxy
    - redis
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_num_4:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - gw_field
    - docker_api_proxy
    - redis
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  cloud_server:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_clock
    - --enable-http
    depends_on:
    - docker_api_proxy
    - gw_cloud_user
    - redis
    - gw_edge_link
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - cloud_user
    - edge_link
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  detector:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_detector
    - --func-param
    - cameras
    - '[{"servient_host": "camera_num_0.field"}, {"servient_host": "camera_num_1.field"},
      {"servient_host": "camera_num_2.field"}, {"servient_host": "camera_num_3.field"},
      {"servient_host": "camera_num_4.field"}]'
    depends_on:
    - gw_field
    - docker_api_proxy
    - redis
    - gw_edge_link
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 600
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field
    - edge_link
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  docker_api_proxy:
    cap_add:
    - ALL
    deploy:
      placement:
        constraints:
        - node.role == manager
    environment:
      CONTAINERS: '1'
      NETWORKS: '1'
      NODES: '1'
      SERVICES: '1'
      TASKS: '1'
    image: tecnativa/docker-socket-proxy
    networks:
    - cloud_user
    - field
    - edge_link
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_cloud_user:
    cap_add:
    - ALL
    command:
    - gateway
    - delay --time 5 --jitter 5 --distribution normal
    - rate --rate 100mbit
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - cloud_user
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_edge_link:
    cap_add:
    - ALL
    command:
    - gateway
    - delay --time 300 --jitter 150 --distribution normal
    - rate --rate 1500kbit
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - edge_link
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_field:
    cap_add:
    - ALL
    command:
    - gateway
    - delay --time 25 --jitter 5 --distribution normal
    - rate --rate 50mbit
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - field
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis:5
    labels:
      org.fundacionctic.wotemu.redis: ''
    networks:
    - cloud_user
    - field
    - edge_link
    ports:
    - '6379'
  user:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_clock
    - --enable-http
    depends_on:
    - docker_api_proxy
    - gw_cloud_user
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - cloud_user
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
version: '3.7'
