networks:
  cloud_user:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: cloud_user
  edge_link_loc1:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: edge_link_loc1
  edge_link_loc2:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: edge_link_loc2
  field_loc1:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: field_loc1
  field_loc2:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.net: ''
    name: field_loc2
  srvnet_mongo_cloud:
    attachable: true
    driver: overlay
    labels:
      org.fundacionctic.wotemu.servicenet: ''
    name: srvnet_mongo_cloud
services:
  camera_loc1_0:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - redis
    - gw_field_loc1
    - docker_api_proxy
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field_loc1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_loc1_1:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - redis
    - gw_field_loc1
    - docker_api_proxy
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field_loc1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_loc2_0:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - redis
    - docker_api_proxy
    - gw_field_loc2
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_loc2_1:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - redis
    - docker_api_proxy
    - gw_field_loc2
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_loc2_2:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - redis
    - docker_api_proxy
    - gw_field_loc2
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_loc2_3:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - redis
    - docker_api_proxy
    - gw_field_loc2
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_loc2_4:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - redis
    - docker_api_proxy
    - gw_field_loc2
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_loc2_5:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - redis
    - docker_api_proxy
    - gw_field_loc2
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_loc2_6:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - redis
    - docker_api_proxy
    - gw_field_loc2
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  camera_loc2_7:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_camera
    - --enable-http
    depends_on:
    - redis
    - docker_api_proxy
    - gw_field_loc2
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 200
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  cloud:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_mongo_historian
    - --func-param
    - mongo_uri
    - mongodb://mongo
    - --func-param
    - observed_things
    - '[{"servient_host": "detector_loc1.edge_link_loc1", "thing_id": "urn:org:fundacionctic:thing:wotemu:detector"},
      {"servient_host": "detector_loc2.edge_link_loc2", "thing_id": "urn:org:fundacionctic:thing:wotemu:detector"}]'
    - --enable-http
    depends_on:
    - redis
    - gw_edge_link_loc2
    - docker_api_proxy
    - gw_cloud_user
    - gw_edge_link_loc1
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - cloud_user
    - edge_link_loc1
    - srvnet_mongo_cloud
    - edge_link_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  detector_loc1:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_detector
    - --func-param
    - cameras
    - '[{"servient_host": "camera_loc1_0.field_loc1"}, {"servient_host": "camera_loc1_1.field_loc1"}]'
    - --enable-http
    depends_on:
    - redis
    - gw_field_loc1
    - gw_edge_link_loc1
    - docker_api_proxy
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 600
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - edge_link_loc1
    - field_loc1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  detector_loc2:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_detector
    - --func-param
    - cameras
    - '[{"servient_host": "camera_loc2_0.field_loc2"}, {"servient_host": "camera_loc2_1.field_loc2"},
      {"servient_host": "camera_loc2_2.field_loc2"}, {"servient_host": "camera_loc2_3.field_loc2"},
      {"servient_host": "camera_loc2_4.field_loc2"}, {"servient_host": "camera_loc2_5.field_loc2"},
      {"servient_host": "camera_loc2_6.field_loc2"}, {"servient_host": "camera_loc2_7.field_loc2"}]'
    - --enable-http
    depends_on:
    - gw_edge_link_loc2
    - redis
    - docker_api_proxy
    - gw_field_loc2
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
      TARGET_CPU_SPEED: 600
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - field_loc2
    - edge_link_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  docker_api_proxy:
    cap_add:
    - ALL
    deploy:
      placement:
        constraints:
        - node.role == manager
    environment:
      CONTAINERS: '1'
      NETWORKS: '1'
      NODES: '1'
      SERVICES: '1'
      TASKS: '1'
    image: tecnativa/docker-socket-proxy
    networks:
    - field_loc2
    - edge_link_loc1
    - edge_link_loc2
    - cloud_user
    - field_loc1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_cloud_user:
    cap_add:
    - ALL
    command:
    - gateway
    - delay --time 5 --jitter 5 --distribution normal
    - rate --rate 100mbit
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - cloud_user
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_edge_link_loc1:
    cap_add:
    - ALL
    command:
    - gateway
    - delay --time 300 --jitter 150 --distribution normal
    - rate --rate 1500kbit
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - edge_link_loc1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_edge_link_loc2:
    cap_add:
    - ALL
    command:
    - gateway
    - delay --time 300 --jitter 150 --distribution normal
    - rate --rate 1500kbit
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - edge_link_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_field_loc1:
    cap_add:
    - ALL
    command:
    - gateway
    - delay --time 25 --jitter 5 --distribution normal
    - rate --rate 50mbit
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - field_loc1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  gw_field_loc2:
    cap_add:
    - ALL
    command:
    - gateway
    - delay --time 25 --jitter 5 --distribution normal
    - rate --rate 50mbit
    depends_on:
    - docker_api_proxy
    - redis
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.gw: ''
    networks:
    - field_loc2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: mongo:4
    labels:
      org.fundacionctic.wotemu.service: ''
    networks:
    - srvnet_mongo_cloud
  redis:
    image: redis:5
    labels:
      org.fundacionctic.wotemu.redis: ''
    networks:
    - field_loc2
    - edge_link_loc1
    - edge_link_loc2
    - cloud_user
    - field_loc1
    ports:
    - '6379'
  user:
    cap_add:
    - ALL
    command:
    - app
    - --path
    - wotemu_caller
    - --func-param
    - servient_host
    - cloud.cloud_user
    - --func-param
    - thing_id
    - urn:org:fundacionctic:thing:historian
    - --func-param
    - params
    - '{"write": null, "list": null}'
    - --func-param
    - lambd
    - '5'
    depends_on:
    - gw_cloud_user
    - redis
    - docker_api_proxy
    deploy:
      replicas: 5
    environment:
      DOCKER_PROXY_URL: tcp://docker_api_proxy:2375/
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      NODE_ID: '{{.Node.ID}}'
      PORT_CATALOGUE: '9090'
      PORT_COAP: '5683'
      PORT_HTTP: '80'
      PORT_MQTT: '1883'
      PORT_WS: '81'
      REDIS_URL: redis://redis
      SERVICE_ID: '{{.Service.ID}}'
      SERVICE_NAME: '{{.Service.Name}}'
    hostname: '{{.Task.Name}}'
    image: agmangas/wotemu
    labels:
      org.fundacionctic.wotemu.node: ''
    networks:
    - cloud_user
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
version: '3.7'
